//
//  IconPack.h
//  Projeect
//
//  Created by Brandon Beecroft on 10/11/14.
//  Copyright (c) 2014 Awesometistic, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface IconPack : NSObject

// Colors
+ (UIColor*)timeBlack;
+ (UIColor*)babyBlue;
+ (UIColor*)snowGray;

// Drawing Methods
+ (void)drawAddicon2;

@end
