//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 10/6/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Colors
+ (UIColor*)timeBlack;
+ (UIColor*)babyBlue;

// Drawing Methods
+ (void)drawAddIcon;

@end
