//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 10/6/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Cache

static UIColor* _timeBlack = nil;
static UIColor* _babyBlue = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _timeBlack = [UIColor colorWithRed: 0.168 green: 0.168 blue: 0.168 alpha: 1];
    _babyBlue = [UIColor colorWithRed: 0.255 green: 0.694 blue: 0.812 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)timeBlack { return _timeBlack; }
+ (UIColor*)babyBlue { return _babyBlue; }

#pragma mark Drawing Methods

+ (void)drawAddIcon;
{

    //// Group
    {
        //// Oval Drawing
        UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(2, 1, 50, 50)];
        [StyleKitName.timeBlack setFill];
        [ovalPath fill];


        //// Text Drawing
        CGRect textRect = CGRectMake(9, -5, 36, 68);
        NSMutableParagraphStyle* textStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        textStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* textFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Avenir-Light" size: 44], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: textStyle};

        [@"+" drawInRect: textRect withAttributes: textFontAttributes];
    }
}

@end
